Algoritmo "soma"
 // disciplina
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/04/2024
Var
// Seção de Declarações das variáveis
 numero1:real,
 numero2:real,
 soma:real


Inicio

Escreva ("digite o primeiro numero")
Leia (numero1)

Escreva ("digite o segunda numero")
Leia (numero2)

soma<-(numero1+numero2)
Escreva ("a soma dos numeros é: ",soma)



      



Fimalgoritmo