Algoritmo "descubra"
 // disciplina
//
// Descrição   : descobre a idade da pessoa (função)
// Autor(a)    : Samuel
// Data atual  : 10/04/2024
Var
// Seção de Declarações das variáveis
 anoA:inteiro
 anoN: inteiro
 idade: inteiro


Inicio

Escreva ("qual seu ano de nascimento")
Leia (anoN)

  anoA<-2024
  
  idade<-(anoA-anoN)
      
      Escreva ("sua idade e", idade)

    
    





      



Fimalgoritmo